# Gauss_Legendre_integration.py

"""
Generating nodes for Gauss-Legendre quadrature over 
[lower_bound, upper_bound] 
using N equal intervals
"""
import numpy as np
    
def GaussLegendre_discretization(lower_bound, upper_bound, N):

    # Zeros of Legendre polynomial P_4(x)
    zer1 = np.sqrt(3./7 - (2./7)*np.sqrt(6./5));
    zer2 = np.sqrt(3./7 + (2./7)*np.sqrt(6./5));

    x_dummy = np.linspace(lower_bound, upper_bound, N+1);
    A = np.array([[1 + zer2, 1 - zer2],
         [1 + zer1, 1 - zer1],
         [1 - zer1, 1 + zer1],
         [1 - zer2, 1 + zer2]]) / 2.;
    x = np.zeros((4*N,));

    for i in range(N):
        x[4*i:4*i+4] = A @ np.array([x_dummy[i],x_dummy[i+1]])
        
    return x

"""
Numerical integration of x(t)*exp(1j*w*t) using Legendre polynomials:
    t: nodes generated by GaussLegendre_discretization function
    x: values of the function at t's
    w: frequency
"""
def legpoly_int(t, x, w):

#*********************************************************************
    # Number of nodes should be 4*N (4,8,...)
    N = int(np.floor(t.size/4))

#*********************************************************************
    # Zeros of the Legendre polynomial P4(x)
    zer1 = np.sqrt(3./7 - (2./7)*np.sqrt(6./5))
    zer2 = np.sqrt(3./7 + (2./7)*np.sqrt(6./5))

#*********************************************************************
    # Gauss-Legendre weights
    weigh1 = (18. + np.sqrt(30.)) / 36.
    weigh2 = (18. - np.sqrt(30.)) / 36.

#*********************************************************************
    # Nodal values of Legendre polynomials
    A = np.array([[1.0000,   -0.8611,    0.6123,   -0.3047],
                  [1.0000,   -0.3400,   -0.3266,    0.4117],
                  [1.0000,    0.3400,   -0.3266,   -0.4117],
                  [1.0000,    0.8611,    0.6123,    0.3047]])

#**********************************************************************
    # Integration
    y = 0.;

    for i in range(N):
        
        da = (t[4*i+2] - t[4*i+3]) / (zer1 - zer2)
        a_avg = (zer1*t[4*i+3] - zer2*t[4*i+2]) / (zer1 - zer2)
        w1 = w * da;
        
        # Integrals of legendre polynomial P0(t),...,P3(t)
        if w == 0.:
           Jp = np.array([1., 0., 0., 0.])
        else:
           # spherical Bessel functions
           Jp = np.array([np.sin(w1)/w1,
                 1j*(np.sin(w1)/w1**2 - np.cos(w1)/w1),
                 -((3./w1**2 - 1)*np.sin(w1)/w1 - 3*np.cos(w1)/w1**2), 
                 -1j*((15./w1**3 - 6./w1)*np.sin(w1)/w1 - (15./w1**2 - 1.)*np.cos(w1)/w1)])
        
        # Coefficients (approximated by Gauss–Legendre quadrature)
        alpha = np.array([0.5,1.5,2.5,3.5]) * \
            (np.array([weigh2*x[4*i],weigh1*x[4*i+1],
                       weigh1*x[4*i+2],weigh2*x[4*i+3]]) @ A)
        
        y += 2*da*np.exp(1j*w*a_avg)*np.sum(alpha*Jp)
        
    return y
